// src/components/dynamic/Project.vue
<script setup lang="ts">
import type { Project } from '@/data/index'

defineProps<{ project: Project }>()
</script>

<template>
  <div class="group relative flex flex-col rounded-xl border border-violet-700 hover:border-violet-400 shadow-md hover:shadow-violet-500 shadow-violet-700 overflow-hidden duration-200 hover:-translate-y-1 backdrop-blur-sm">
    <!-- Image area with hover description overlay -->
    <div class="relative h-72 md:h-96 overflow-hidden">
      <img
        v-if="project.image"
        :src="project.image"
        :alt="project.name"
        class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
      />
      <div
        v-else
        class="w-full h-full bg-gradient-to-br from-violet-900/60 to-slate-800"
      />

      <!-- Description overlay on hover -->
      <div class="absolute inset-0 bg-slate-950/90 flex items-center justify-center p-6 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
        <p class="text-sm md:text-base poppins text-slate-200 text-center leading-relaxed">
          {{ project.description }}
        </p>
      </div>
    </div>

    <!-- Bottom: name + GitHub + tech tags -->
    <div class="flex flex-col gap-3 p-5">
      <div class="flex items-center justify-between">
        <h3 class="text-lg md:text-xl font-semibold poppins">{{ project.name }}</h3>
        <a
          :href="project.link"
          target="_blank"
          class="text-xl md:text-2xl hover:text-cyan-400 duration-200 fa-brands fa-github"
        ></a>
      </div>
      <div class="flex flex-wrap gap-x-3 gap-y-1">
        <span v-for="lang in project.langs" :key="lang" class="text-xs md:text-sm tech-mono text-cyan-300">
          {{ lang }}
        </span>
      </div>
    </div>
  </div>
</template>

// src/components/dynamic/Project.svelte
<script>
  export let project;

  let showPic = false;
  const togglePicture = () => {
    showPic = !showPic;
  }
</script>

<div
  class="flex flex-col gap-4 p-4 text-center duration-200 border border-solid rounded-lg shadow-md hover:shadow-lg hover:-translate-y-[2px] hover:-skew-y-1 sm:p-6 md:p-8 border-violet-700 group hover:border-violet-400 hover:shadow-violet-500 shadow-violet-700 backdrop-blur-sm"
>
  <div class="flex justify-center">
    <button
      class="p-2 text-2xl duration-200 bg-transparent rounded-full hover:bg-violet-700 hover:bg-opacity-40 hover:shadow-md hover:shadow-violet-300"
      on:click={togglePicture}
    >
      {#if showPic}
        <i class="fas fa-eye-slash"></i>
        {:else}
          <i class="fas fa-eye"></i>
      {/if}
    </button>
  </div>
  <a
    href={project.link}
    target="_blank"
    class="self-end w-4 -mt-16 text-2xl rounded-full cursor-pointer md:text-4xl hover:text-cyan-400 fa-brands fa-github"
  >
  </a>
  <div
    class="grid mx-auto text-5xl duration-200 place-items-center md:text-5xl"
  >
    <h3 class="pb-2 text-xl font-medium sm:text-3xl md:text-4xl">{project.name}</h3>
    {#if showPic}
      <img
        src={project.image}
        alt={project.name}
        class="bg-slate-800 md:w-full md:h-full"
      />
      {:else}
        <p class="text-sm md:text-xl sm:text-lg poppins">{project.description}</p>
    {/if}
  </div>
  <div class="grid items-center grid-cols-3 gap-2 mt-5 align-bottom md:grid-cols-3 lg:grid-cols-4">
    {#each project.langs as lang}
      <p class="text-sm md:text-lg tech-mono">{lang}</p>
    {/each}
  </div>
</div>
