// src/components/sections/Experience.vue
<script setup lang="ts">
import { ref } from 'vue'
import ExperienceCard from '@/components/dynamic/ExperienceCard.vue'

const experienceLabels = [
  'Software Engineer',
  'Co-Founder & CTO',
  'Full-Stack Developer',
  'Junior Full-Stack Developer',
  'Backend Developer',
  'Intern Backend Developer',
]

const experienceIndex = ref(0)
</script>

<template>
  <section id="experience" class="grid items-center grid-cols-1">
    <p class="pb-5 text-center md:pb-10 section-title">02. Experience</p>
    <div class="grid grid-cols-1 gap-10 lg:grid-cols-2 lg:gap-10 place-items-center backdrop-blur-sm">
      <ul class="space-y-5 border-l-2">
        <li v-for="(label, i) in experienceLabels" :key="i">
          <button
            @click="experienceIndex = i"
            :class="[
              'p-5 text-lg sm:text-xl md:text-2xl lg:text-3xl cursor-pointer hover:text-cyan-400 poppins',
              experienceIndex === i ? 'border-l-4 border-cyan-400 duration-200 text-cyan-400 font-semibold' : ''
            ]"
          >
            {{ label }}
          </button>
        </li>
      </ul>

      <div :key="experienceIndex" class="animate-fade-right">
        <ExperienceCard :experienceIndex="experienceIndex" />
      </div>
    </div>
  </section>
</template>

// src/components/sections/Experience.svelte
<script>
    import ExperienceCard from "../dynamic/ExperienceCard.svelte";
    
    let currentExperience = "exp1";
    let experienceIndex = 0;
    var expCard;
    const changeExperienceCard = (e) => {
        currentExperience = e.target.id;
        if (currentExperience == "exp1") {
            experienceIndex = 0;
        } else if (currentExperience == "exp2") {
            experienceIndex = 1;
        } else if (currentExperience == "exp3") {
            experienceIndex = 2;
        } else if (currentExperience == "exp4") {
            experienceIndex = 3;
        } else if (currentExperience == "exp5") {
            experienceIndex = 4;
        }
    }
</script>

<style>
    .experience-list-item {
        @apply p-5 text-lg sm:text-xl md:text-2xl lg:text-3xl cursor-pointer hover:text-cyan-400
    }

    .activexp {
        @apply border-l-4 border-cyan-400 duration-200 text-cyan-400 font-semibold;
    }
</style>

<section id="experience" class="grid items-center grid-cols-1">
    <p class="pb-5 text-center md:pb-10 section-title">02. Experience</p>
    <div class="grid grid-cols-1 gap-10 lg:grid-cols-2 lg:gap-10 place-items-center backdrop-blur-sm">
        <ul class="space-y-5 border-l-2">
            <li>
                <button id="exp1" on:click={changeExperienceCard} class="experience-list-item poppins" class:activexp={currentExperience === "exp1"}>Co-Founder & CTO</button>

            </li>
            <li>
                <button id="exp2" on:click={changeExperienceCard} class="experience-list-item poppins" class:activexp={currentExperience === "exp2"}>Full-Stack Engineer</button>

            </li>
            <li>
                <button id="exp3" on:click={changeExperienceCard} class="experience-list-item poppins" class:activexp={currentExperience === "exp3"}>Backend Academy Golang</button>

            </li>
            <li>
                <button id="exp4" on:click={changeExperienceCard} class="experience-list-item poppins" class:activexp={currentExperience === "exp4"}>Junior Full-Stack Developer</button>
            </li>
            <li>
                <button id="exp5" on:click={changeExperienceCard} class="experience-list-item poppins" class:activexp={currentExperience === "exp5"}>Internship Backend Ruby on Rails</button>
            </li>
        </ul>

        {#key experienceIndex}
            <div class="animate-fade-right">
                <ExperienceCard experienceIndex={experienceIndex} />
            </div>
        {/key}
    </div>
</section>
